const API_BASE_URL_DEVELOPMENT = 'https://localhost:7219'
const API_BASE_URL_PRODUCTION = 'https://aspnetcorereactpractice-aspnetserver.azurewebsites.net'

const ENDPOINTS = {
    GET_ALL_GAMES: 'api/videoGame',
    GET_ONE_GAME_BY_ID: 'api/videoGame',
    CREATE_GAME: 'api/videoGame',
    UPDATE_ONE_GAME_BY_ID: 'api/videoGame',
    DELETE_ONE_GAME_BY_ID: 'api/videoGame',
}

const development = {
    API_URL_GET_ALL_GAMES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_GAMES}`,
    API_URL_GET_ONE_GAME_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ONE_GAME_BY_ID}`,
    API_URL_CREATE_GAME: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_GAME}`,
    API_URL_UPDATE_ONE_GAME_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_ONE_GAME_BY_ID}`,
    API_URL_DELETE_ONE_GAME_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_ONE_GAME_BY_ID}`
}

const production = {
    API_URL_GET_ALL_GAMES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_GAMES}`,
    API_URL_GET_ONE_GAME_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ONE_GAME_BY_ID}`,
    API_URL_CREATE_GAME: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_GAME}`,
    API_URL_UPDATE_ONE_GAME_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_ONE_GAME_BY_ID}`,
    API_URL_DELETE_ONE_GAME_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_ONE_GAME_BY_ID}`
}

const Constants = process.env.NODE_ENV === 'development' ? development : production

export default Constants